#!/data/data/com.termux/files/usr/bin/bash

# Get the URL
URL=$1
echo "Opening URL"

# Cheks if its Youtube or Spotify URL and downloads it
if [[ $URL == *"open.spotify.com"* ]] ; then
  echo "Spotify link detected"
  if [[ $URL == *"playlist"* ]]; then
    echo "Downloading Playlist"
    spotifydl $URL -o /storage/emulated/0/Download
  fi
  if [[ $URL == *"track"* ]]; then
    echo "Downloading Song"
    spotifydl $URL -o /storage/emulated/0/Download
  fi
  if  [[ $URL == *"album"* ]]; then
    echo "Downloading Album"
    spotifydl $URL -o /storage/emulated/0/Download
  fi
elif  [[ $URL == *"youtu.be"* || $URL == *"youtube.com"* ]]; then
  formatvar=0
  read -p $'What do you want to download \n(Select the number and press enter) \n 1) Video \n 2) Audio \n' formatvar
  if [[ $formatvar == 1 ]]; then
    read -p $'Do you want to download the subtitles for this video? \n(Select the number and press enter) \n 1) Yes \n 2) No \n' formatvar
    if [[ $formatvar == 1 ]]; then
      echo 'Downloading Video with subtitles'
      youtube-dl --all-subs $URL      
    elif [[ $formatvar == 2 ]]; then
      echo 'Downloading Video'
      youtube-dl $URL
    fi
  elif [[ $formatvar == 2 ]]; then
      echo 'downloading Audio'
      youtube-dl -x --audio-format 'mp3' $URL
  else
    echo 'Default downloading Video'
    youtube-dl $URL
  fi

else
  echo "No downloader for this URL type"
fi

read -n 1 -s -p "Press any key to exit..."
